services:
  medusa_db:
    container_name: medusa_db
    image: postgres
    environment:
      POSTGRES_USER: medusa
      POSTGRES_PASSWORD: medusa
      POSTGRES_DB: medusa
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'medusa', '-U', 'medusa']
      interval: 30s
      timeout: 10s
      retries: 5
