services:
  medusa_db:
    container_name: medusa_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - medusa_db_vol:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'medusa', '-U', 'medusa']
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  medusa_db_vol:
